
version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/app
      PORT: 3001
    ports:
      - "3001:3001"

  web:
    build: ./web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:3001
    ports:
      - "3000:3000"

volumes:
  db_data:
